import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import Header from './components/Header';

// --- DEFINIÇÃO DOS DADOS DO HEADER NO LAYOUT RAÍZ ---
// O Layout Raiz é o 'Pai' e fornece os dados.
const SITE_TITLE = "ADEFS"; // Exemplo de Título
const NAV_LINKS = [
    { name: "Início", url: "/" },
    { name: "Sobre", url: "/about" },
    { name: "Projetos", url: "/projects" },
    { name: "Contato", url: "/contact" },
];
// ----------------------------------------------------

const inter = Inter({ 
  subsets: ['latin'],
  // O 'variable' permite que se use 'font-inter' como uma classe CSS (Tailwind)
  variable: '--font-inter',
});

export const metadata: Metadata = {
    title: SITE_TITLE,
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} antialiased`}
            >
                {/* 🎯 SOLUÇÃO: O Header agora recebe as props obrigatórias */}
                <Header 
                    title={SITE_TITLE} 
                    links={NAV_LINKS} 
                />

                {/* {children} representa o conteúdo da página atual (ex: /about, /contact) */}
                <main>{children}</main>
            </body>
        </html>
    );
}